name: ci

on:
  # Run manually
  workflow_dispatch:

  push:
    # Run on push to main or master
    branches: [ main, master ]
    # Run when push any tag
    tags: ['v*']
  # Run on PR to main or master
  pull_request:
    branches: [ main, master ]

jobs:
  # run tests in all workspaces
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npm run pw:install

      - name: Run Playwright tests
        run: npm run pw:test

        # https://github.com/actions/upload-artifact
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # https://docs.codecov.com/docs/quick-start
      - name: Upload client test coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
          files: ./packages/client/coverage/coverage-final.json

      # https://docs.codecov.com/docs/quick-start
      - name: Upload server test coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: server
          files: ./packages/server/coverage/coverage-final.json



  # deploy client
  deploy-client:
    runs-on: ubuntu-latest

    # ensure tests pass
    needs: test

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # docker metadata
      # https://github.com/docker/metadata-action
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # the image to use as base for tags
          images: "${{ vars.DOCKERHUB_USERNAME }}/sketched-client"
          # tags to generate
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      # enable multi-platform builds
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # use BuildKit
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build and Push Docker image
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./packages/client/Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max



  # deploy client
  deploy-server:
    runs-on: ubuntu-latest

    # ensure tests pass
    needs: test

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # docker metadata
      # https://github.com/docker/metadata-action
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # the image to use as base for tags
          images: "${{ vars.DOCKERHUB_USERNAME }}/sketched-server"
          # tags to generate
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      # enable multi-platform builds
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # use BuildKit
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build and Push Docker image
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./packages/server/Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max
