name: ci

on:
  push:
    # Run when push any branch
    branches: ['**']
    # Run when push any tag
    tags: ['*']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # run tests in all workspaces
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # https://docs.codecov.com/docs/quick-start
      - name: Upload client test coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
          files: ./packages/client/coverage/coverage-final.json

      # https://docs.codecov.com/docs/quick-start
      - name: Upload server test coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: server
          files: ./packages/server/coverage/coverage-final.json

  # deploy client
  deploy-client:
    runs-on: ubuntu-latest

    # ensure tests pass
    needs: test

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      # enable multi-platform builds
      # https://github.com/docker/setup-qemu-action
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # use BuildKit
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build and Push Docker image (main)
      # https://github.com/docker/build-push-action
      - name: Build and push (main)
        uses: docker/build-push-action@v6
        # Only on branch
        if: startsWith(github.ref, 'refs/heads/')
        with:
          context: ./packages/client
          push: true
          tags: "${{ vars.DOCKERHUB_USERNAME }}/sketched-client:${{ github.sha }}"
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # build and Push Docker image (tag)
      # https://github.com/docker/build-push-action
      - name: Build and push (tag)
        uses: docker/build-push-action@v6
        # Only on tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: ./packages/client
          push: true
          # tag as both ref and latest
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sketched-client:latest
            ${{ secrets.DOCKER_USERNAME }}/sketched-client:${{ github.ref_name }}
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # deploy client
  deploy-server:
    runs-on: ubuntu-latest

    # ensure tests pass
    needs: test

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      # enable multi-platform builds
      # https://github.com/docker/setup-qemu-action
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # use BuildKit
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build and Push Docker image (main)
      # https://github.com/docker/build-push-action
      - name: Build and push (main)
        uses: docker/build-push-action@v6
        # Only on branch
        if: startsWith(github.ref, 'refs/heads/')
        with:
          context: ./packages/server
          push: true
          tags: "${{ vars.DOCKERHUB_USERNAME }}/sketched-server:${{ github.sha }}"
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # build and Push Docker image (tag)
      # https://github.com/docker/build-push-action
      - name: Build and push (tag)
        uses: docker/build-push-action@v6
        # Only on tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: ./packages/server
          push: true
          # tag as both ref and latest
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sketched-server:latest
            ${{ secrets.DOCKER_USERNAME }}/sketched-server:${{ github.ref_name }}
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha
          cache-to: type=gha,mode=max
